apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: redis-cluster
  region: us-east-1
nodeGroups:
- name: ng-1
  instanceType: t2.micro
  desiredCapacity: 2
  ssh:
    allow: true
    publicKeyPath: ~/.ssh/id_rsa.pub
cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator"]
