apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: "/mnt/data"


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
    - image: redis
      name: redisdb
      ports:
        - containerPort: 6379
          protocol: TCP
      volumeMounts:
        - name: redis-data
          mountPath: "/data"
    volumes:
    - name: redis-data
      persistentVolumeClaim:
        claimName: redis-pvc



  # selector:
  #   app: mango-server
  #   tier: mango-server


