apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
    - image: redis
      name: redisdb
      ports:
        - containerPort: 6379
          protocol: TCP
      volumeMounts:
        - name: redis-data
          mountPath: "/data"
    volumes:
    - name: redis-data
      persistentVolumeClaim:
        claimName: redis-pvc



  # selector:
  #   app: mango-server
  #   tier: mango-server


