apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  label:
    app: storage
    environment: test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: "/mnt/data"
